# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: William Huang
title: Senior Software Development Manager
email: elviswilliamhk@gmail.com
website: will-hk.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: githistory
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  - Over a decade of experience turning ideas into reality via <mark>technology</mark>
  - Years of experience <mark>leading development teams</mark>
  - Unique understanding of what <mark>agile</mark> is and more importantly, what it is not
  - Unique ability to <mark>sympathize and synergize</mark> with developers
  - Profound understanding of developer needs, what makes them tick, and what makes great dev teams
  - Profound understanding of team and (perverse) <mark>incentive management</mark>
  - Profound knowledge in distributed ledger technologies and <mark>decentralized finance</mark>
  - Years of knowledge in <mark>finance</mark> including insurance, FX, options, futures, structured products, etc.
  - Years of experience in design and development of <mark>large-scale, complex financial systems</mark>
  - Years of <mark>innovation</mark> turning technology into solutions that solve real world problems
  - Deep involvement in full <mark>SDLC</mark> including
    - Requirement gathering
    - Counter proposal
    - Solution design
    - Work analysis / distribution
    - Implementation
    - Testing
    - Code review
    - Change management
    - Feedback management

content:
  #- title: Projects # Title for the section
    #layout: list # Type of content section (list/text)
    #content:
      #- layout: top-middle
        #title: Super awesome project
        #link: github.com/sproogen
        ## link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          ## - title:  Github page for project (eg. sproogen/modern-resume-theme)
          ##   icon: fab fa-github
          ##   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
          #I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HSBC
        link: hsbc.com
        # link_text: boringcompany.com
        sub_title: Senior Software Development Manager, Structured Products
        caption: Sep 2018 - Present
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Designing, developing and delivering the next-gen high performance OMS for HSBC's structured products line of offerings using proprietary as well as open-source software.

      - layout: left
        title: HSBC
        link: hsbc.com
        # link_text: boringcompany.com
        sub_title: Senior Development Specialist, FX
        caption: May 2016 - Oct 2017
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Implementation and support of the FX trading frontend utilizing the then cutting-edge technologies.

      - layout: left
        title: Compare Global Group
        link: moneyhero.com
        # link_text: boringcompany.com
        sub_title: Lead Developer / CTO
        caption: Sep 2015 - Apr 2016
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Leading a team of developers working on CGG's financial / subcription product comparison line of business, helping consumers get the most of what's on offer by the banks / insurance firms / ISPs, etc.

      - layout: left
        title: AXA
        link: axa.com
        # link_text: boringcompany.com
        sub_title: Full Stack Development Lead
        caption: Sep 2014 - Aug 2015
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Leading a team of developers working on AXA's strategic digital transformation solutions making traditional insurance products more accessible to customers.

      - layout: left
        title: Maaii
        link: maaiiconnect.com
        # link_text: boringcompany.com
        sub_title: Head of Web Development
        caption: Mar 2012 - Aug 2014
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Building the customer facing portal for Maaii (Now Cinnox), helping customers find, use and enjoy Maaii's offerings.

      - layout: left
        title: IBM
        link: ibm.com
        # link_text: boringcompany.com
        sub_title: Web Production Lead
        caption: Jul 2010 - Feb 2012
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Creating innovations and solutions for reliable delivery of IBM's clients' online presence.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Hong Kong Baptist University
        caption: Sep 2008 - Sep 2009
        sub_title: MA in Financial Journalism

      - layout: top
        title: Shanghai International Studies University
        caption: Sep 2003 - Jun 2007
        sub_title: BA in English Language and Literature

  - title: Qualifications
    layout: list
    content:
      - layout: top
        title: IBM Six-Sigma Green Belt
        caption: Aug 2011

      - layout: top
        title: IBM RSU (Restricted Stock Units) Grant
        caption: Jun 2011

      - layout: top
        title: Test of English as a Foreign Language (TOEFL)
        caption: Jun 2007

      - layout: top
        title: Test for English Majors Level 8 (TEM8)
        caption: Mar 2007

      - layout: top
        title: Certificate for Senior Interpreters (CSI, Shanghai)
        caption: May 2006

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Knowledge
        - options
        - futures
        - equity derivatives
        - FX

      - Tools
        - git / svn / cvs
        - gerrit / jenkins
        - tmux / vim / sublime text
        - docker / fig / kubernetes
        - greasemonkey / tampermonkey
        - ssh / sftp / smb / webdav
        - plantuml

      - Technologies
        - Angular / Polymer / Custome Elements
        - GraphQL / JWT / PWA
        - angularjs / ember / backbone
        - bootstrap / foundation
        - jquery / dojo
        - express / wintersmith / metalsmith / harp / hapi
        - nodebb / wordpress / cakephp / moodle / opencart
        - npm / bower / yeoman
        - underscore / lodash / Q / bluebird / async / RxJS
        - mocha / phantomjs / casperjs / nightwatch / karma / protractor
        - chaijs / sinonjs / jasmine
        - grunt / brunch / gulp
        - scrapy / cheerio / iconv(-lite)
        - mongodb / mysql / redis / cayley
        - phonegap / ionic

      - Programming Languages
        - CoffeeScript
        - JavaScript
        - HTML
        - Jade
        - CSS
        - SASS / SCSS
        - Python
        - PHP
        - Go
        - VB(A)
        - C++
        - C
        - Assembly

      - Patterns & Standards
        - RESTful API (CRUD operations)
        - Dependency Injection
        - Micro Service Architecture
        - Unit / Integration / E2E Testing

      - Servers
        - NodeJS
        - Apache
        - NginX
        - Bind
        - Postfix

      - Operating Systems
        - Linux ( Preferred Dev OS )
        - OSX
        - Windows

  - title: On Innovation
    layout: text
    content: | # this will include new lines to allow paragraphs
      Most organizations / teams tend to confuse innovation with technology, thinking technology means innovation. The more advanced technologies you use, the better you can innovate. And that's why a lot of teams focus their attention on technology. But is that the right thing to do?

      IMHO, innovations are often realized through technological means, which means technology is only the means to the end. Innovation should be based on real life needs. Those tangible needs are the source of inspiration for innovations. Innovation should be led and driven by those needs. If we're able to solve real world problems in creative and effective ways, then it doesn't really matter how much technology is involved.

  - title: On Incentive Management
    layout: text
    content: | # this will include new lines to allow paragraphs
      In a factory operated 100% by machines, you feed them electricity and they work. How much they work depends on how much electricity is fed. But if we treat humans as machine-like resources (I guess that's why we use the term "human resource"), using money (like electricity) as the sole means to drive them, then we'd be missing a lot of potential efficiency and loyalty. I believe this "factory mindset" is exactly the primary culprit behind so many teams' low morale and high attrition rate. If managing humans is as easy as managing machines, then why do we need managers at all?

      Innovation, for example, is one such area where more money doesn't necessarily mean more productivity. You can't say "I'll pay you X amount of money and please give me Y number of innovations by date Z". Apart from "problem / need discovery ability" mentioned above, another important moving factor here is <mark>incentive</mark>. Are your people willing to innovate? Do they feel safe to innovate? Why not?

      How about sharing? Are your developers willing to offer help to rest of the team? Do they have a collective success / failure mindset?

      How about morale? Do your developers offer to do what's above and beyond what they're assigned to? Are they willing to take on more responsibilities than described in the JD? Are they speaking their minds during work?

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
